# Generated by Django 2.2.19 on 2022-09-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tovar_link', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('chaina_link', models.URLField(max_length=500)),
                ('opponents_link', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razmer', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('ves', models.FloatField()),
                ('kolichestvo_na_sklade_marketplase', models.IntegerField()),
                ('kolichestvo_na_sklade_home', models.IntegerField()),
                ('id_tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tovar', to='tovar.Tovar')),
            ],
        ),
    ]
