# Generated by Django 2.2.19 on 2022-09-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tovar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakup_date', models.DateTimeField()),
                ('course_USD', models.FloatField()),
                ('course_CNY', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tovar_v_zakupku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_china', models.FloatField()),
                ('kollichestvo', models.IntegerField()),
                ('price_delivery', models.FloatField()),
                ('SKU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovar_v_zakup', to='tovar.SKU')),
                ('id_zakup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovar_v_zakup', to='zakupka.Zakup')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovar_v_zakup', to='tovar.Tovar')),
            ],
        ),
    ]
