# Generated by Django 2.2.19 on 2022-09-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tovar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('В обработке', 'В обработке'), ('Отменено', 'Отменено'), ('Доставлен', 'Доставлен')], default='В обработке', max_length=50)),
                ('arrive_date', models.DateTimeField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tovar_v_zakaze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
                ('commission', models.IntegerField()),
                ('SKU', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakazy', to='tovar.SKU')),
                ('id_tovara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakazy', to='tovar.Tovar')),
                ('id_zakaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tovary', to='zakaz.Zakaz')),
            ],
        ),
    ]
